token = "xxx" # your github token which can write the following repo
github_proxy = "" # example: https://hub.gitmirror.com/, end with "/".
                  # Use this type of proxy for direct access, provided for Chinese users.

[repo]
owner = ""
repo = "" # repo name
path = "" # relative directory path inside repo

[committer]
name = "name"
email = "name@users.noreply.github.com"